# Generated by Django 4.1.6 on 2023-02-16 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listner',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='Listingwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
